### ISSUE TITLE
Consider contributing changes to the original aws_sqs module

### ISSUE THREAD

**Issue by DieterHolvoet** [wieni/wmqueue_sqs#1]
Consider contributing changes to the original [`aws_sqs`](https://www.drupal.org/project/aws_sqs) module instead of creating a hard fork.

## Code to contribute

*   [ ] Add prefix option
    *   [ ] changes in `AwsSqsQueue::createQueue`
    *   [ ] changes in `AwsSqsQueueFactory::get`
*   [ ] Cast `$waitTimeSeconds` and `$claimTimeout` to int (AwsSqsQueue.php)

## TODO's

*   [ ] Add new prefix option to settings form
*   [ ] Check if data size limit is 64kb (Validate, link to documentation).
*   [ ] Add error handling, in case service becomes unavailable
